-- ============================================================================
-- V2 — Core domain: users, events, seats, bookings
-- ----------------------------------------------------------------------------
-- Schema is the source of truth (Flyway). Hibernate runs with ddl-auto=validate,
-- so column names/types/nullability here must match the JPA entities exactly.
--
-- Concurrency note: overselling is prevented at TWO layers.
--   1) Application: optimistic @Version on seats + (optionally) SELECT FOR UPDATE.
--   2) Database: the seats.version column and the (event_id, seat_label) unique
--      constraint guarantee that even buggy/edge concurrent writes cannot create
--      duplicate seats or silently lose updates.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
CREATE TABLE events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    description    TEXT,
    venue          VARCHAR(255) NOT NULL,
    event_datetime TIMESTAMPTZ  NOT NULL,
    total_capacity INTEGER      NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT chk_events_capacity CHECK (total_capacity >= 0)
);

-- Common browse/search filters: upcoming events, by venue, by date.
CREATE INDEX idx_events_datetime ON events (event_datetime);
CREATE INDEX idx_events_venue     ON events (venue);

-- ---------------------------------------------------------------------------
-- seats
-- ---------------------------------------------------------------------------
CREATE TABLE seats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT       NOT NULL DEFAULT 0,   -- optimistic lock token
    event_id        BIGINT       NOT NULL,
    seat_label      VARCHAR(16)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'AVAILABLE',
    held_by_user_id BIGINT,
    hold_expires_at TIMESTAMPTZ,
    booking_id      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_seats_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT uq_seats_event_label UNIQUE (event_id, seat_label),
    CONSTRAINT chk_seats_status CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED'))
);

-- Availability lookups for an event ("show me free seats") hit this hard.
CREATE INDEX idx_seats_event_status ON seats (event_id, status);
-- The scheduled release job scans for HELD seats whose hold has lapsed.
CREATE INDEX idx_seats_hold_expiry  ON seats (status, hold_expires_at);

-- ---------------------------------------------------------------------------
-- bookings
-- ---------------------------------------------------------------------------
CREATE TABLE bookings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    event_id     BIGINT      NOT NULL,
    status       VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    seat_count   INTEGER     NOT NULL,
    expires_at   TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_bookings_user  FOREIGN KEY (user_id)  REFERENCES users (id),
    CONSTRAINT fk_bookings_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT chk_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT chk_bookings_seatcount CHECK (seat_count > 0)
);

-- "My bookings" and the expiry sweep over PENDING bookings.
CREATE INDEX idx_bookings_user        ON bookings (user_id);
CREATE INDEX idx_bookings_status_exp  ON bookings (status, expires_at);

-- Now that bookings exists, point seats.booking_id at it. (Created here rather
-- than inline above to avoid a forward reference / circular table dependency.)
ALTER TABLE seats
    ADD CONSTRAINT fk_seats_booking
    FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE SET NULL;
