-- ============================================================================
-- V3 — Payments + pricing model
-- ----------------------------------------------------------------------------
-- Forward-only migration (Flyway). Adds:
--   1) A money/pricing model on events and seats so prices live in the DB, not
--      in frontend code. Bookings freeze the payable amount at hold time.
--   2) A first-class `payments` table with an idempotency key so repeated /pay
--      calls cannot charge twice, plus useful lookup indexes.
--   3) An index on seats(booking_id) — booking read/confirm/cancel all query
--      seats by booking id.
--
-- All new columns are added with sensible NOT NULL DEFAULTs (or are nullable),
-- so the existing create-event flow and pre-V3 rows remain valid. Hibernate runs
-- with ddl-auto=validate, so columns/types/nullability here mirror the entities.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- events: currency + base price + per-seat convenience fee (minor units)
-- ---------------------------------------------------------------------------
ALTER TABLE events
    ADD COLUMN currency              VARCHAR(3) NOT NULL DEFAULT 'INR',
    ADD COLUMN base_price_minor      BIGINT     NOT NULL DEFAULT 0,
    ADD COLUMN convenience_fee_minor BIGINT     NOT NULL DEFAULT 0;

ALTER TABLE events ADD CONSTRAINT chk_events_base_price CHECK (base_price_minor >= 0);
ALTER TABLE events ADD CONSTRAINT chk_events_fee        CHECK (convenience_fee_minor >= 0);

-- ---------------------------------------------------------------------------
-- seats: optional tier name + optional per-seat price (NULL = use event base)
-- ---------------------------------------------------------------------------
ALTER TABLE seats
    ADD COLUMN tier_name   VARCHAR(40),
    ADD COLUMN price_minor BIGINT;

ALTER TABLE seats ADD CONSTRAINT chk_seats_price CHECK (price_minor IS NULL OR price_minor >= 0);

-- Booking-scoped seat lookups (response mapping, confirm, cancel, expiry release).
CREATE INDEX idx_seats_booking ON seats (booking_id);

-- ---------------------------------------------------------------------------
-- bookings: freeze the payable amount at hold time so checkout can't reprice
-- ---------------------------------------------------------------------------
ALTER TABLE bookings
    ADD COLUMN currency     VARCHAR(3) NOT NULL DEFAULT 'INR',
    ADD COLUMN amount_minor BIGINT     NOT NULL DEFAULT 0,
    ADD COLUMN fee_minor    BIGINT     NOT NULL DEFAULT 0;

ALTER TABLE bookings ADD CONSTRAINT chk_bookings_amount CHECK (amount_minor >= 0);
ALTER TABLE bookings ADD CONSTRAINT chk_bookings_fee    CHECK (fee_minor >= 0);

-- ---------------------------------------------------------------------------
-- payments: one row per payment attempt, idempotent per (booking, key)
-- ---------------------------------------------------------------------------
CREATE TABLE payments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id         BIGINT       NOT NULL,
    user_id            BIGINT       NOT NULL,
    idempotency_key    VARCHAR(100) NOT NULL,
    amount_minor       BIGINT       NOT NULL,
    currency           VARCHAR(3)   NOT NULL DEFAULT 'INR',
    status             VARCHAR(16)  NOT NULL,
    provider_reference VARCHAR(120),
    failure_reason     VARCHAR(255),
    created_at         TIMESTAMPTZ  NOT NULL,
    updated_at         TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_payments_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    -- The idempotency guard: the same booking+key can never produce two rows, so
    -- two concurrent /pay calls with the same key cannot both charge. Whichever
    -- INSERT loses the race gets a unique violation and replays the winner's result.
    CONSTRAINT uq_payments_booking_key UNIQUE (booking_id, idempotency_key),
    CONSTRAINT chk_payments_status CHECK (status IN ('INITIATED', 'APPROVED', 'DECLINED', 'FAILED')),
    CONSTRAINT chk_payments_amount CHECK (amount_minor >= 0)
);

-- Lookups: "payments for this booking" and "payments by this user".
CREATE INDEX idx_payments_booking ON payments (booking_id);
CREATE INDEX idx_payments_user    ON payments (user_id);
